main: ${main.class}
name: ${project.name}
version: ${project.version}
description: A simple Minecraft plugin to grab system info/specs
author: Dylan Hansch
website: https://dylanhansch.net
commands:
    cpu:
        description: View CPU specs
        usage: /<command>
    java:
        description: View Java (JRE) info
        usage: /<command>
    os:
        description: View OS info
        usage: /<command>
    run:
        description: Run Linux commands
        usage: /<command>
    top:
        description: Linux top command
        usage: /<command>
